development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: cube_app_development
  pool: 5
  username: azuma
  password: azuma1224
  socket: /tmp/mysql.sock
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: cube_app_test
  pool: 5
  username: azuma
  password: azuma1224
  socket: /tmp/mysql.sock
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: cube_app_production
  pool: 5
  username: azuma
  password: azuma1224
  socket: /tmp/mysql.sock
  host: localhost